Fix yaml.load by using default Loader class
This doesn't work on Mac M1:

      AttributeError: module 'yaml' has no attribute 'CLoader'

It's unclear why we used a more specific class originally [^1]. We
are only loading small YAML files, so the specific loader shouldn't
make a difference, especially as we trust the source data.

[^1]: https://github.com/alphagov/notifications-govuk-alerts/commit/bca67c0cb7262a6e669726bd8d30fc2373bc47f3#diff-b70bfb027a8ef3ec4ab07a53a3b8ba83e63334ba3ce5ca6d9d773900ed452e5eR44